sudo: false
services: mongodb
language: node_js
node_js:
  - 6.11.1
cache:
  directories:
    - node_modules
    - client/bower_components
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
### SCRIPTS ###
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rvm install 2.2
  - gem install sass
  - npm install -g bower grunt-cli
  - bower install
  - echo 'repo_token '$COVERALLS_REPO_TOKEN > .coveralls.yml
after_success:
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
