sudo: false
services: mongodb
language: node_js
node_js:
  - 4.2.1
cache:
  directories:
    - node_modules
    - client/bower_components
matrix:
  allow_failures:
    - node_js: '0.12'
    - node_js: '0.11'
    - node_js: '0.10'
    - node_js: 'iojs'
### SCRIPTS ###
before_script:
  - gem install sass
  - npm install -g bower grunt-cli
  - bower install
  - echo 'repo_token '$COVERALLS_REPO_TOKEN > .coveralls.yml
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
