sudo: false
services: mongodb
language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
matrix:
  allow_failures:
    - 0.11
before_script:
  - npm install -g bower grunt-cli
  - bower install
cache:
  directories:
    - node_modules
    - client/bower_components