sudo: false
cache:
  directories:
  - node_modules
  - bower_components
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
deploy:
  provider: openshift
  user: jens.brimberg@gmail.com
  password:
    secure: Dsjy3k5LUEn+cKoZlTS80TM8IgbqEEzRIFk5vh6ruAmGgN7E2epJs2A9eBdfIs8HA5n5BiHik+vLjJva5AL+Ui8IdKbaovQ1sukfxh3sHNwPkpcnNAB4tUmqkGhHYbNQ5/IYq/8Uj5trYaEsDi25+SIAlt9KXIqZ1w6CUW42Az6C+T83gRzI36ISvrWdJRH150/7J2k6aWqBCzQRWWERbP9Cj5iYgrG4rXQTZJ0Wn1GnOnlTMFunlWx7hQ5cph/IkjvShIXVdhRn/2HG+DPvXKuyFW1EgAdPOgCNJxbbF8LgUYJBuD4zJ9ZywrlXaCdbD9aMWhl6ZgUErO5S+6LIlxyXIX28HmYz77KS5DaAK72RJVoHN4EaCzXuVnlnI3tJM3r4FxeRQ/TavlId39BEyuSqcbLK9+LGcAljeKB2+YjmyAtG5+oomF5bH1r32xdSw6kJdTlm65JgoCaZCOB5W04qXmc8PrNg/B7Mex2jk5mCT/BsPj7engn1sZYnbS78vG5XqyI6dlUG6n+j20iuaH0CnPKWopLUMeVp0BHko3nZ/38NXzprrFu1phggPK5xrbNf8tQNpAzdZpDiogGvkwufKVb99iHwFJ7/YXTlUWSyhlT+07691XJTYMH8fu6K0EKnntoRXEgsG9Ot+AqmB345ptvGpSlojFUh+RJH3Ok=
  app: dd
  domain: dd
  on:
    repo: jensim/dd
