sudo: false
services: mongodb
language: node_js
node_js:
  - 6.11.1
cache:
  directories:
    - node_modules
    - client/bower_components
### SCRIPTS ###
before_script:
  - gem install sass
  - npm install -g bower grunt-cli
  - bower install
  - echo 'repo_token '$COVERALLS_REPO_TOKEN > .coveralls.yml
after_success:
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
