sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
env:
  - NODE_ENV='test'
services: mongodb
matrix:
  allow_failures:
    - node_js: 'iojs'
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
